/**
 * CSS Custom Properties writer (FR-007).
 * Generates design-system.css with tokens grouped by category.
 * Gradients are NOT included in CSS — only in JSON (FR-007).
 */

import type { AllTokens } from '../types/tokens.js';
import { allocateCssTokenNames } from '../utils/css-token-names.js';

function quoteCssString(value: string): string {
  const escaped = value.replace(/["\\\u0000-\u001f\u007f]/g, (character) => {
    if (character === '"' || character === '\\') return `\\${character}`;
    if (character === '\u0000') return '\ufffd';
    return `\\${character.charCodeAt(0).toString(16)} `;
  });
  return `"${escaped}"`;
}

/**
 * Generate CSS Custom Properties string from extracted tokens.
 * Token masking: no API token appears in output (FR-018).
 */
export function generateCSS(tokens: AllTokens, fileId?: string): string {
  const lines: string[] = [];
  const names = allocateCssTokenNames(tokens);

  lines.push('/* Generated by FrameProof. Do not edit manually. */');
  if (fileId) {
    lines.push(`/* Source: Figma file ${fileId} */`);
  }
  lines.push(`/* Generated: ${new Date().toISOString()} */`);
  lines.push('');
  lines.push(':root {');

  // Colors
  if (tokens.colors.length > 0) {
    lines.push(`  /* Colors (${tokens.colors.length} unique, sorted by usage) */`);
    for (const color of names.colors) {
      lines.push(`  --${color.name}: ${color.token.value_hex};`);
    }
    lines.push('');
  }

  // Typography
  if (tokens.typography.length > 0) {
    lines.push(`  /* Typography (${tokens.typography.length} styles) */`);

    for (const family of names.fontFamilies) {
      lines.push(`  --${family.name}: ${quoteCssString(family.value)}, sans-serif;`);
    }
    for (const size of names.fontSizes) {
      lines.push(`  --${size.name}: ${size.value}px;`);
    }
    for (const weight of names.fontWeights) {
      lines.push(`  --${weight.name}: ${weight.value};`);
    }
    lines.push('');
  }

  // Spacing
  if (tokens.spacing.length > 0) {
    lines.push(`  /* Spacing (${tokens.spacing.length} values) */`);
    for (const spacing of names.spacing) {
      lines.push(`  --${spacing.name}: ${spacing.token.value}px;`);
    }
    lines.push('');
  }

  // Border Radius
  if (tokens.radii.length > 0) {
    lines.push(`  /* Border Radius (${tokens.radii.length} values) */`);
    for (const radius of names.radii) {
      lines.push(`  --${radius.name}: ${radius.token.value}px;`);
    }
    lines.push('');
  }

  // Shadows
  if (tokens.shadows.length > 0) {
    lines.push(`  /* Shadows (${tokens.shadows.length}) */`);
    for (const shadow of names.shadows) {
      lines.push(`  --${shadow.name}: ${shadow.token.css};`);
    }
    lines.push('');
  }

  lines.push('}');

  return lines.join('\n') + '\n';
}
