/**
 * CSS Custom Properties writer (FR-007).
 * Generates design-system.css with tokens grouped by category.
 * Gradients are NOT included in CSS — only in JSON (FR-007).
 */

import type { AllTokens } from '../types/tokens.js';

/**
 * Generate CSS Custom Properties string from extracted tokens.
 * Token masking: no API token appears in output (FR-018).
 */
export function generateCSS(tokens: AllTokens, fileId?: string): string {
  const lines: string[] = [];

  lines.push('/* Generated by figma-scaler. Do not edit manually. */');
  if (fileId) {
    lines.push(`/* Source: Figma file ${fileId} */`);
  }
  lines.push(`/* Generated: ${new Date().toISOString()} */`);
  lines.push('');
  lines.push(':root {');

  // Colors
  if (tokens.colors.length > 0) {
    lines.push(`  /* Colors (${tokens.colors.length} unique, sorted by usage) */`);
    for (const color of tokens.colors) {
      lines.push(`  --color-${color.name}: ${color.value_hex};`);
    }
    lines.push('');
  }

  // Typography
  if (tokens.typography.length > 0) {
    lines.push(`  /* Typography (${tokens.typography.length} styles) */`);

    const families = new Set<string>();
    const sizes = new Set<number>();
    const weights = new Set<number>();

    for (const t of tokens.typography) {
      families.add(t.font_family);
      sizes.add(t.font_size);
      weights.add(t.font_weight);
    }

    for (const family of families) {
      const varName = family.toLowerCase().replace(/\s+/g, '-');
      lines.push(`  --font-family-${varName}: '${family}', sans-serif;`);
    }
    for (const size of [...sizes].sort((a, b) => a - b)) {
      lines.push(`  --font-size-${size}: ${size}px;`);
    }
    for (const weight of [...weights].sort((a, b) => a - b)) {
      lines.push(`  --font-weight-${weight}: ${weight};`);
    }
    lines.push('');
  }

  // Spacing
  if (tokens.spacing.length > 0) {
    lines.push(`  /* Spacing (${tokens.spacing.length} values) */`);
    for (const s of tokens.spacing) {
      lines.push(`  --spacing-${s.value}: ${s.value}px;`);
    }
    lines.push('');
  }

  // Border Radius
  if (tokens.radii.length > 0) {
    lines.push(`  /* Border Radius (${tokens.radii.length} values) */`);
    for (const r of tokens.radii) {
      lines.push(`  --radius-${r.value}: ${r.value}px;`);
    }
    lines.push('');
  }

  // Shadows
  if (tokens.shadows.length > 0) {
    lines.push(`  /* Shadows (${tokens.shadows.length}) */`);
    for (const s of tokens.shadows) {
      lines.push(`  --${s.name}: ${s.css};`);
    }
    lines.push('');
  }

  lines.push('}');

  return lines.join('\n') + '\n';
}
