/**
 * T024 — CSS writer tests.
 *
 * Tests the generateCSS function which takes AllTokens and produces a
 * CSS custom properties string grouped by category inside :root {}.
 *
 * Coverage:
 * - Generates valid CSS with :root {} wrapper
 * - Groups tokens by category (Colors, Typography, Spacing, Radius, Shadows)
 * - Uses kebab-case variable names (--color-*, --font-*, --spacing-*, --radius-*)
 * - Includes file header comment with source info
 * - Handles empty tokens (no sections generated)
 * - fileId parameter is optional
 * - Does NOT include gradients in CSS output (FR-007)
 * - Validates generated CSS is parseable using css-tree
 */

import { describe, it, expect } from 'vitest';
import { parse } from 'css-tree';
import { generateCSS } from '../../../src/writers/css.js';
import type {
  AllTokens,
  ColorToken,
  GradientToken,
  TypographyToken,
  SpacingToken,
  RadiusToken,
  ShadowToken,
} from '../../../src/types/tokens.js';

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

/** Fully-populated AllTokens fixture for testing all sections. */
const fullTokens: AllTokens = {
  colors: [
    {
      name: 'brand-primary',
      node_id: '1:2',
      source_type: 'fill',
      value_hex: '#2563eb',
      value_rgba: { r: 37, g: 99, b: 235, a: 1 },
      opacity: 1,
      usage_count: 2,
      used_in_types: ['RECTANGLE'],
    },
    {
      name: 'text-dark',
      node_id: '1:3',
      source_type: 'fill',
      value_hex: '#111827',
      value_rgba: { r: 17, g: 24, b: 39, a: 1 },
      opacity: 1,
      usage_count: 1,
      used_in_types: ['TEXT'],
    },
  ],
  gradients: [
    {
      name: 'gradient-linear-1',
      node_id: '1:6',
      gradient_type: 'LINEAR',
      stops: [
        { position: 0, color_hex: '#2563eb', color_rgba: { r: 37, g: 99, b: 235, a: 1 } },
        { position: 1, color_hex: '#8e44f4', color_rgba: { r: 142, g: 68, b: 244, a: 1 } },
      ],
      handle_positions: [
        { x: 0, y: 0.5 },
        { x: 1, y: 0.5 },
      ],
    },
  ],
  typography: [
    {
      name: 'heading-xl',
      node_id: '1:3',
      font_family: 'Inter',
      font_size: 32,
      font_weight: 700,
      font_style: 'normal',
      line_height: '40px',
      line_height_px: 40,
      letter_spacing: -0.5,
      text_align_horizontal: 'LEFT',
      text_case: 'ORIGINAL',
      text_decoration: 'NONE',
      sample_text: 'Welcome to Design System',
      usage_count: 1,
    },
    {
      name: 'body-regular',
      node_id: '1:4',
      font_family: 'Roboto',
      font_size: 16,
      font_weight: 400,
      font_style: 'normal',
      line_height: '24px',
      line_height_px: 24,
      letter_spacing: 0,
      text_align_horizontal: 'LEFT',
      text_case: 'ORIGINAL',
      text_decoration: 'NONE',
      sample_text: 'Body text example',
      usage_count: 3,
    },
  ],
  spacing: [
    { value: 8, source: 'padding', usage_count: 2 },
    { value: 12, source: 'item_spacing', usage_count: 1 },
    { value: 16, source: 'padding', usage_count: 3 },
  ],
  radii: [
    { value: 4, is_per_corner: false, usage_count: 3 },
    { value: 8, is_per_corner: false, usage_count: 1 },
    { value: 12, is_per_corner: false, usage_count: 1 },
  ],
  shadows: [
    {
      name: 'shadow-drop-1',
      node_id: '1:2',
      shadow_type: 'DROP_SHADOW',
      offset_x: 0,
      offset_y: 2,
      blur: 4,
      spread: 0,
      color_hex: '#0000001a',
      color_rgba: { r: 0, g: 0, b: 0, a: 0.1 },
      css: '0px 2px 4px 0px rgba(0, 0, 0, 0.1)',
    },
    {
      name: 'shadow-inner-1',
      node_id: '1:6',
      shadow_type: 'INNER_SHADOW',
      offset_x: 0,
      offset_y: 1,
      blur: 2,
      spread: 0,
      color_hex: '#0000000d',
      color_rgba: { r: 0, g: 0, b: 0, a: 0.05 },
      css: 'inset 0px 1px 2px 0px rgba(0, 0, 0, 0.05)',
    },
  ],
  images: [],
  components: [],
};

/** AllTokens with all arrays empty. */
const emptyTokens: AllTokens = {
  colors: [],
  gradients: [],
  typography: [],
  spacing: [],
  radii: [],
  shadows: [],
  images: [],
  components: [],
};

// ---------------------------------------------------------------------------
// Tests — file header comment with source info
// ---------------------------------------------------------------------------

describe('generateCSS — header', () => {
  const css = generateCSS(fullTokens);

  it('output starts with a CSS comment header', () => {
    expect(css.trimStart().startsWith('/*')).toBe(true);
  });

  it('header contains "Generated by figma-scaler"', () => {
    expect(css).toContain('Generated by figma-scaler');
  });

  it('header contains "Do not edit manually"', () => {
    expect(css).toContain('Do not edit manually');
  });

  it('header includes a Generated timestamp', () => {
    expect(css).toMatch(/Generated:\s+\d{4}-\d{2}-\d{2}T/);
  });
});

describe('generateCSS — fileId in header', () => {
  it('includes source file ID comment when fileId is provided', () => {
    const css = generateCSS(fullTokens, 'abc123XYZ');
    expect(css).toContain('Source: Figma file abc123XYZ');
  });

  it('omits source comment when fileId is not provided', () => {
    const css = generateCSS(fullTokens);
    expect(css).not.toContain('Source: Figma file');
  });
});

// ---------------------------------------------------------------------------
// Tests — fileId parameter is optional
// ---------------------------------------------------------------------------

describe('generateCSS — fileId is optional', () => {
  it('can be called with only tokens (no fileId)', () => {
    expect(() => generateCSS(fullTokens)).not.toThrow();
  });

  it('can be called with tokens and fileId', () => {
    expect(() => generateCSS(fullTokens, 'my-file-id')).not.toThrow();
  });

  it('can be called with tokens and undefined fileId', () => {
    expect(() => generateCSS(fullTokens, undefined)).not.toThrow();
  });

  it('produces valid CSS in both cases', () => {
    const withoutId = generateCSS(fullTokens);
    const withId = generateCSS(fullTokens, 'file123');
    expect(withoutId).toContain(':root {');
    expect(withId).toContain(':root {');
  });
});

// ---------------------------------------------------------------------------
// Tests — :root {} wrapper
// ---------------------------------------------------------------------------

describe('generateCSS — :root {} wrapper', () => {
  const css = generateCSS(fullTokens);

  it('contains :root { selector', () => {
    expect(css).toContain(':root {');
  });

  it('contains closing brace for :root', () => {
    const rootIndex = css.indexOf(':root {');
    const afterRoot = css.slice(rootIndex);
    expect(afterRoot).toContain('}');
  });

  it('all custom properties are inside :root block', () => {
    // Extract the :root block
    const rootStart = css.indexOf(':root {');
    const rootEnd = css.lastIndexOf('}');
    const rootBlock = css.slice(rootStart, rootEnd + 1);

    // Find all -- declarations in the entire CSS
    const allVarDecls = [...css.matchAll(/--([\w-]+)\s*:/g)];
    // Find all -- declarations inside :root
    const rootVarDecls = [...rootBlock.matchAll(/--([\w-]+)\s*:/g)];

    expect(allVarDecls.length).toBe(rootVarDecls.length);
    expect(allVarDecls.length).toBeGreaterThan(0);
  });
});

// ---------------------------------------------------------------------------
// Tests — Groups tokens by category
// ---------------------------------------------------------------------------

describe('generateCSS — Colors section', () => {
  const css = generateCSS(fullTokens);

  it('contains a Colors section comment', () => {
    expect(css).toMatch(/\/\*.*Colors/i);
  });

  it('Colors comment shows correct count', () => {
    expect(css).toContain(`Colors (${fullTokens.colors.length} unique, sorted by usage)`);
  });

  it('contains --color- prefixed CSS variables', () => {
    expect(css).toMatch(/--color-[\w-]+:/);
  });

  it('includes the brand primary color value', () => {
    expect(css).toContain('--color-brand-primary: #2563eb;');
  });

  it('includes the text-dark color value', () => {
    expect(css).toContain('--color-text-dark: #111827;');
  });
});

describe('generateCSS — Typography section', () => {
  const css = generateCSS(fullTokens);

  it('contains a Typography section comment', () => {
    expect(css).toMatch(/\/\*.*Typography/i);
  });

  it('Typography comment shows correct count', () => {
    expect(css).toContain(`Typography (${fullTokens.typography.length} styles)`);
  });

  it('includes --font-family- variables', () => {
    expect(css).toMatch(/--font-family-[\w-]+:/);
  });

  it('includes --font-size- variables', () => {
    expect(css).toMatch(/--font-size-\d+:/);
  });

  it('includes --font-weight- variables', () => {
    expect(css).toMatch(/--font-weight-\d+:/);
  });

  it('font family values include sans-serif fallback', () => {
    expect(css).toMatch(/--font-family-inter:.*sans-serif/);
  });

  it('generates unique font families from multiple typography tokens', () => {
    // Inter and Roboto should both appear
    expect(css).toContain('--font-family-inter');
    expect(css).toContain('--font-family-roboto');
  });

  it('font sizes are sorted ascending', () => {
    const sizePattern = /--font-size-(\d+):/g;
    const sizes: number[] = [];
    let match: RegExpExecArray | null;
    while ((match = sizePattern.exec(css)) !== null) {
      sizes.push(parseInt(match[1], 10));
    }
    expect(sizes.length).toBeGreaterThan(0);
    for (let i = 1; i < sizes.length; i++) {
      expect(sizes[i]).toBeGreaterThanOrEqual(sizes[i - 1]);
    }
  });

  it('font weights are sorted ascending', () => {
    const weightPattern = /--font-weight-(\d+):/g;
    const weights: number[] = [];
    let match: RegExpExecArray | null;
    while ((match = weightPattern.exec(css)) !== null) {
      weights.push(parseInt(match[1], 10));
    }
    expect(weights.length).toBeGreaterThan(0);
    for (let i = 1; i < weights.length; i++) {
      expect(weights[i]).toBeGreaterThanOrEqual(weights[i - 1]);
    }
  });
});

describe('generateCSS — Spacing section', () => {
  const css = generateCSS(fullTokens);

  it('contains a Spacing section comment', () => {
    expect(css).toMatch(/\/\*.*Spacing/i);
  });

  it('Spacing comment shows correct count', () => {
    expect(css).toContain(`Spacing (${fullTokens.spacing.length} values)`);
  });

  it('includes --spacing- prefixed variables', () => {
    expect(css).toMatch(/--spacing-\d+:/);
  });

  it('includes all spacing values in px', () => {
    expect(css).toContain('--spacing-8: 8px;');
    expect(css).toContain('--spacing-12: 12px;');
    expect(css).toContain('--spacing-16: 16px;');
  });
});

describe('generateCSS — Border Radius section', () => {
  const css = generateCSS(fullTokens);

  it('contains a Border Radius section comment', () => {
    expect(css).toMatch(/\/\*.*Border Radius/i);
  });

  it('Border Radius comment shows correct count', () => {
    expect(css).toContain(`Border Radius (${fullTokens.radii.length} values)`);
  });

  it('includes --radius- prefixed variables', () => {
    expect(css).toMatch(/--radius-\d+:/);
  });

  it('includes all radius values in px', () => {
    expect(css).toContain('--radius-4: 4px;');
    expect(css).toContain('--radius-8: 8px;');
    expect(css).toContain('--radius-12: 12px;');
  });
});

describe('generateCSS — Shadows section', () => {
  const css = generateCSS(fullTokens);

  it('contains a Shadows section comment', () => {
    expect(css).toMatch(/\/\*.*Shadow/i);
  });

  it('Shadows comment shows correct count', () => {
    expect(css).toContain(`Shadows (${fullTokens.shadows.length})`);
  });

  it('includes shadow CSS values', () => {
    expect(css).toContain('0px 2px 4px 0px rgba(0, 0, 0, 0.1)');
    expect(css).toContain('inset 0px 1px 2px 0px rgba(0, 0, 0, 0.05)');
  });

  it('shadow variables use the token name', () => {
    expect(css).toContain('--shadow-drop-1:');
    expect(css).toContain('--shadow-inner-1:');
  });
});

// ---------------------------------------------------------------------------
// Tests — kebab-case variable names
// ---------------------------------------------------------------------------

describe('generateCSS — kebab-case variable names', () => {
  const css = generateCSS(fullTokens);

  it('all CSS custom properties use kebab-case (lowercase, hyphens, digits only)', () => {
    const varPattern = /--([\w-]+)\s*:/g;
    const matches = [...css.matchAll(varPattern)];
    expect(matches.length).toBeGreaterThan(0);

    for (const match of matches) {
      const name = match[1];
      // kebab-case: only lowercase letters, digits, and hyphens
      expect(name).toMatch(/^[a-z0-9]+(-[a-z0-9]+)*$/);
    }
  });

  it('color variables use --color-* pattern', () => {
    const colorVars = [...css.matchAll(/--color-([\w-]+)\s*:/g)];
    expect(colorVars.length).toBe(fullTokens.colors.length);
  });

  it('font variables use --font-* pattern', () => {
    const fontVars = [...css.matchAll(/--font-([\w-]+)\s*:/g)];
    expect(fontVars.length).toBeGreaterThan(0);
  });

  it('spacing variables use --spacing-* pattern', () => {
    const spacingVars = [...css.matchAll(/--spacing-([\w-]+)\s*:/g)];
    expect(spacingVars.length).toBe(fullTokens.spacing.length);
  });

  it('radius variables use --radius-* pattern', () => {
    const radiusVars = [...css.matchAll(/--radius-([\w-]+)\s*:/g)];
    expect(radiusVars.length).toBe(fullTokens.radii.length);
  });
});

// ---------------------------------------------------------------------------
// Tests — Gradients NOT included in CSS (FR-007)
// ---------------------------------------------------------------------------

describe('generateCSS — does NOT include gradients (FR-007)', () => {
  const css = generateCSS(fullTokens);

  it('does not contain "gradient" in any variable name', () => {
    expect(css).not.toMatch(/--gradient/i);
  });

  it('does not contain a Gradients section comment', () => {
    expect(css).not.toMatch(/\/\*\s*Gradient/i);
  });

  it('does not output gradient stop colors as gradient tokens', () => {
    // The gradient has specific stop colors; ensure no gradient-specific section
    // (colors may appear in the colors section, but not as gradient tokens)
    const lines = css.split('\n');
    const gradientLines = lines.filter(
      (l) => l.includes('gradient') && !l.includes('Generated by'),
    );
    expect(gradientLines).toHaveLength(0);
  });
});

// ---------------------------------------------------------------------------
// Tests — empty tokens (no sections generated)
// ---------------------------------------------------------------------------

describe('generateCSS — empty tokens', () => {
  const css = generateCSS(emptyTokens);

  it('produces valid CSS even with empty tokens', () => {
    expect(css).toContain(':root {');
    expect(() => {
      parse(css);
    }).not.toThrow();
  });

  it('does not generate a Colors section when no colors exist', () => {
    expect(css).not.toMatch(/\/\*.*Colors/i);
  });

  it('does not generate a Typography section when no typography exists', () => {
    expect(css).not.toMatch(/\/\*.*Typography/i);
  });

  it('does not generate a Spacing section when no spacing exists', () => {
    expect(css).not.toMatch(/\/\*.*Spacing/i);
  });

  it('does not generate a Border Radius section when no radii exist', () => {
    expect(css).not.toMatch(/\/\*.*Border Radius/i);
  });

  it('does not generate a Shadows section when no shadows exist', () => {
    expect(css).not.toMatch(/\/\*.*Shadow/i);
  });

  it('contains no custom property declarations', () => {
    const varPattern = /--([\w-]+)\s*:/g;
    const matches = [...css.matchAll(varPattern)];
    expect(matches).toHaveLength(0);
  });

  it('still has the header and :root block', () => {
    expect(css).toContain('Generated by figma-scaler');
    expect(css).toContain(':root {');
    expect(css).toContain('}');
  });
});

// ---------------------------------------------------------------------------
// Tests — valid CSS (css-tree validation)
// ---------------------------------------------------------------------------

describe('generateCSS — valid CSS (css-tree validation)', () => {
  it('full tokens produce parseable CSS', () => {
    const css = generateCSS(fullTokens);
    expect(() => {
      parse(css);
    }).not.toThrow();
  });

  it('empty tokens produce parseable CSS', () => {
    const css = generateCSS(emptyTokens);
    expect(() => {
      parse(css);
    }).not.toThrow();
  });

  it('CSS with fileId produces parseable output', () => {
    const css = generateCSS(fullTokens, 'test-file-id');
    expect(() => {
      parse(css);
    }).not.toThrow();
  });

  it('CSS with only colors produces parseable output', () => {
    const colorsOnly: AllTokens = {
      ...emptyTokens,
      colors: fullTokens.colors,
    };
    const css = generateCSS(colorsOnly);
    expect(() => {
      parse(css);
    }).not.toThrow();
  });

  it('CSS with only typography produces parseable output', () => {
    const typographyOnly: AllTokens = {
      ...emptyTokens,
      typography: fullTokens.typography,
    };
    const css = generateCSS(typographyOnly);
    expect(() => {
      parse(css);
    }).not.toThrow();
  });
});

// ---------------------------------------------------------------------------
// Tests — output ends with newline
// ---------------------------------------------------------------------------

describe('generateCSS — output formatting', () => {
  it('output ends with a trailing newline', () => {
    const css = generateCSS(fullTokens);
    expect(css.endsWith('\n')).toBe(true);
  });

  it(':root closing brace is on its own line', () => {
    const css = generateCSS(fullTokens);
    const lines = css.split('\n');
    const closingLine = lines.find((l) => l.trim() === '}');
    expect(closingLine).toBeDefined();
  });
});
